# Главное меню в шапке

[[main]]
  name = "Концепция"
  pageRef = "concept"
  weight = 10

[[main]]
  name = "Площадка"
  pageRef = "site"
  weight = 20

[[main]]
  name = "Экономика"
  pageRef = "economics"
  weight = 30

[[main]]
  name = "Дорожная карта"
  pageRef = "roadmap"
  weight = 40

[[main]]
  name = "Прометей-РФ"
  pre = "star"
  pageRef = "phases/phase-05"
  weight = 50

[[main]]
  name = "Опция B"
  pageRef = "option-b"
  weight = 60

[[main]]
  name = "Конкуренты"
  pageRef = "competitors"
  weight = 70

[[main]]
  name = "Блог"
  pageRef = "blog"
  weight = 80

[[main]]
  name = "Поддержать"
  pre = "heart"
  pageRef = "support"
  weight = 90

# Подвал

[[footer]]
  name = "Об авторе"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "Контакты"
  pageRef = "contact"
  weight = 20

[[footer]]
  name = "История изменений"
  pageRef = "changelog"
  weight = 30
